const ROLES = {
  ADMIN: 'ADMIN',
  MANAGER: 'MANAGER',
  STAFF: 'STAFF'
};

const MOVEMENT_TYPES = {
  IN: 'IN',
  OUT: 'OUT',
  TRANSFER_IN: 'TRANSFER_IN',
  TRANSFER_OUT: 'TRANSFER_OUT',
  ADJUSTMENT: 'ADJUSTMENT'
};

const ALERT_TYPES = {
  LOW_STOCK: 'LOW_STOCK',
  OUT_OF_STOCK: 'OUT_OF_STOCK'
};

const ALERT_STATUSES = {
  ACTIVE: 'ACTIVE',
  RESOLVED: 'RESOLVED'
};

const ENTITY_STATUSES = {
  ACTIVE: 'ACTIVE',
  INACTIVE: 'INACTIVE'
};

module.exports = {
  ROLES,
  MOVEMENT_TYPES,
  ALERT_TYPES,
  ALERT_STATUSES,
  ENTITY_STATUSES
};
